# .graphclientrc.yml
sources:
  - name: txs-ethereum
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ekrembal/railgun-ethereum-v2-txids
  - name: txs-goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ekrembal/railgun-goerli-v2-txids

documents:
  - ./railgun-txids-query.graphql
